### ISSUE TITLE
Link?

### ISSUE THREAD

**Issue by jonabaptistella** [jenstornell/panel-brand#3]
Just ask; Any way to use this as to add a link for an support page or similar in the top?

**Comment by jenstornell** [comment]
I wish that would be possible but it's not, because I can't use javascript, only CSS.

https://forum.getkirby.com/t/why-would-global-panel-js-be-more-unsafe-than-a-field-js/5557

If I would make it a field instead that would be possible but then the field would be required on every template and it would stop working on files pages and the dashboard. It's possible to add a widget and a file field as well but then it would be much work for the user to add it to every place and I bet I've missed some places.

My choice is to just wait it out to have Kirby Panel to catch up. Thanks anyway for the idea.
